"""watch progress and favorites

Revision ID: 012e0dd4d543
Revises: e57f1712b021
Create Date: 2026-09-15 03:39:23.683541

"""
import sqlalchemy as sa
from alembic import op

revision = '012e0dd4d543'
down_revision = 'e57f1712b021'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('favorites',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('movie_slug', sa.String(length=255), nullable=False),
    sa.Column('movie_name', sa.String(length=255), nullable=False),
    sa.Column('poster_url', sa.String(length=2048), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'movie_slug', name='uq_favorite_user_movie')
    )
    op.create_index(op.f('ix_favorites_movie_slug'), 'favorites', ['movie_slug'], unique=False)
    op.create_index(op.f('ix_favorites_user_id'), 'favorites', ['user_id'], unique=False)
    op.create_table('watch_progress',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('movie_slug', sa.String(length=255), nullable=False),
    sa.Column('movie_name', sa.String(length=255), nullable=False),
    sa.Column('poster_url', sa.String(length=2048), nullable=True),
    sa.Column('episode_slug', sa.String(length=255), nullable=False),
    sa.Column('episode_name', sa.String(length=255), nullable=False),
    sa.Column('server_name', sa.String(length=255), nullable=True),
    sa.Column('position_seconds', sa.Integer(), nullable=False),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'movie_slug', 'episode_slug', name='uq_progress_user_movie_episode')
    )
    op.create_index(op.f('ix_watch_progress_movie_slug'), 'watch_progress', ['movie_slug'], unique=False)
    op.create_index(op.f('ix_watch_progress_user_id'), 'watch_progress', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_watch_progress_user_id'), table_name='watch_progress')
    op.drop_index(op.f('ix_watch_progress_movie_slug'), table_name='watch_progress')
    op.drop_table('watch_progress')
    op.drop_index(op.f('ix_favorites_user_id'), table_name='favorites')
    op.drop_index(op.f('ix_favorites_movie_slug'), table_name='favorites')
    op.drop_table('favorites')
    # ### end Alembic commands ###
