"""index refresh_tokens expires_at

Revision ID: e0976b6afeb9
Revises: 012e0dd4d543
Create Date: 2026-09-15 07:32:40.970543

"""
from alembic import op

revision = 'e0976b6afeb9'
down_revision = '012e0dd4d543'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_refresh_tokens_expires_at'), 'refresh_tokens', ['expires_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_refresh_tokens_expires_at'), table_name='refresh_tokens')
    # ### end Alembic commands ###
